// console.log('this is node js ')
// console.log('this is node js ')
// console.log('this is node js ')
// process.exit(1)
const { ford, tesla } = require('./car')
// console.log(tesla)
// console.log(ford)
console.log(JSON.stringify(tesla, null, 2))
console.log(JSON.stringify(ford, undefined, 2))
